### ISSUE TITLE
Has anyone tried internationalization of validation messages using yup + i18next?

### ISSUE THREAD

**Issue by jorisre** [react-hook-form/resolvers#102]
Has anyone tried internationalization of validation messages using yup + i18next?

Yup provides a way to do this using [setLocale()](https://github.com/jquense/yup#using-a-custom-locale-dictionary), however it doesn't seem to work with RHF. For example, I have used `setLocale` like this:

```
yup.setLocale({
    mixed: {
        default: 'fieldInvalid',
        required: 'fieldRequired',
    },
    string: {
        required: 'fieldRequired',
    },
});
```

However, RHF seems to ignore it completely and I still get validation messages like "Email is a required field" instead of "fieldRequired" which I can send to i18next for translation.

_Originally posted by @nareshbhatia in https://github.com/react-hook-form/react-hook-form/discussions/3808_

**Comment by joaopaulobdac** [comment]
I ran into the same problem here but I managed to fix it.

[According to jquense](https://github.com/jquense/yup/issues/293#issuecomment-414450125) you have to call `setLocale` before constructing the schema. I thought I was already doing this because I was setting the locale in the root index.tsx file of my project:
```tsx
// index.tsx
import { render } from 'react-dom'
import { setLocale } from 'yup'
import { ptShort } from 'yup-locale-pt'

setLocale(ptShort)

render(<App />, document.getElementById('root'))
```
But it wasn't working. I don't know why.

So I just set the locale in the same file as the schema to be extremely clear about it:
```tsx
// component.tsx
import { setLocale, object } from 'yup'
import { ptShort } from 'yup-locale-pt'

setLocale(ptShort)

const formSchema = object({
})
```
Now that works.

Unfortunately I don't think it's possible to share schemas between the backend and frontend using different locales because of this.

**Comment by jorisre** [comment]
Thanks @joaopaulobdac 👍🏻 

@nareshbhatia maybe a possible solution/workaround

**Comment by iamclaytonray** [comment]
A better solution would be returning a key from the validation object and then wrapping that key in `t()` in your component
