### ISSUE TITLE
yupResolver doesnt work in IE11 since upgrading v1.3.6

### ISSUE THREAD

**Issue by jcolakk** [react-hook-form/resolvers#143]
Hi, I upgraded @hookform/resolvers to v1.3.6 and the import paths changed. Before, we imported the `yupResolver` from `@hookform/resolvers/dist/ie11/yup`, and now I imported it from `@hookform/resolvers/yup/dist/yup` and it broke IE11. 

Is IE11 not supported anymore by @hookform/resolvers?

**Comment by jorisre** [comment]
Aaaargh, sorry, I forgot IE11.. :/ 
Thanks for reporting, I can fix it tomorrow

ℹ️  We still support IE11 in version 1.X but we don't in version 2.X

**Comment by jcolakk** [comment]
No worries :) thanks for the fast response 👍 
I guess this is a duplicate of this issue: https://github.com/react-hook-form/resolvers/issues/84

**Comment by jorisre** [comment]
@jcolakk Should be good now, can you confirm ? Thanks

**Comment by jcolakk** [comment]
Yes, works now, thanks a lot! 👍

**Comment by m3fawner** [comment]
Just want to drop a message of thanks for @jorisre . Appreciate the quick fix for ie11!

**Comment by Joshgrant-dev** [comment]
Hey all, sorry to bump this issue. 

I downloaded v1.3.7 of this and having the same issue as seen above:
![image](https://user-images.githubusercontent.com/82834818/115371645-71d23780-a1ca-11eb-9031-4a3fd9b9c91f.png)

`import { yupResolver } from '@hookform/resolvers/dist/ie11/yup';` is all I'm doing for reference.

Have I missed a trick? IE11 is really important to me so need the ability to support that.

Thanks in advance!

**Comment by jorisre** [comment]
@Joshgrant-dev Can you check your node_modules have the correct version, same for your yarn.lock or package-lock.json ?

**Comment by Joshgrant-dev** [comment]
> 
> 
> @Joshgrant-dev Can you check your node_modules have the correct version, same for your yarn.lock or package-lock.json ?

![image](https://user-images.githubusercontent.com/82834818/115375068-b90df780-a1cd-11eb-88b6-45bc0273fc6f.png)
![image](https://user-images.githubusercontent.com/82834818/115375111-c3c88c80-a1cd-11eb-9dcf-7bda733a4851.png)


Deleted my node_modules and yarn.lock and still coming up with this issue annoyingly!

Thanks for the quick response by the way! Is the code snippet below the correct directory to import from or am I mistaken? Because that's what I can see on other docs.

`import { yupResolver } from '@hookform/resolvers/dist/ie11/yup';`

**Comment by davepoon** [comment]
I am facing the same issue with versin 1.3.7, then I have to import it like this in order to avoid the **Module not found** issue.
`import { yupResolver } from "@hookform/resolvers/dist/ie11/yup/yup";`
