### ISSUE TITLE
Superstruct: Array attribute types error an array of errors instead of an object for errors

### ISSUE THREAD

**Issue by coreyjv** [react-hook-form/resolvers#160]
**Describe the bug**

When using superstruct resolver with an `array` field type the the `error` object is an `array` instead of an object per the [React Hook Form documentation](https://react-hook-form.com/api/useformstate).

**To Reproduce**

1. Go to https://codesandbox.io/s/competent-kalam-v98vd?file=/src/App.js
2. Click on "Submit Query" button
3. Observe the `arrayField` errors property is an array instead of an object. This is the unexpected behavior.
4. Observe that `nonArrayField` errors property is an object as expected.

**Expected behavior**

Per the documentation the errors for a field should be an object with a `message` and `type` property and not an array. 

**Desktop (please complete the following information):**

- OS: MacOS 10.15.7
- Browser: Firefox
- Version 88.0b4

**Additional context**

In this instance it appears that [parseErrorSchema](https://github.com/react-hook-form/resolvers/blob/master/superstruct/src/superstruct.ts#L7) produces an object like this:

```
  { "arrayField.0": { "message": "Expected one of `"John,"Jane"`, but received: "Bill"", "type": "enums" } }
```

which when passed to `toNestError` from `@hookform/resovlers` returns an `Array`

**Comment by jorisre** [comment]
Hi @coreyjv 

Sorry for the late reply.

We generate form errors based on validation library result, in your case, the result of superstruct look likes that:
<img width="656" alt="Screenshot 2021-04-29 at 22 41 18" src="https://user-images.githubusercontent.com/7545547/116615923-470b8000-a93c-11eb-8675-f4439b694d0b.png">

We follow the given path to format form errors, that's why you get an array of errors.

As an alternative, you can use the [custom-refinements](https://docs.superstructjs.org/api-reference/refinements#custom-refinements) to validate yourself the value.

@bluebill1049 Any idea ? thanks

**Comment by bluebill1049** [comment]
That's right @jorisre we follow the path, this path looks strange to me, I am not sure how we can support that.

**Comment by coreyjv** [comment]
@jorisre and @bluebill1049 -- For what it's worth I was trying out the yup resolver and it behaves in the same fashion.

**Comment by jorisre** [comment]
@coreyjv Did you find a solution?

**Comment by coreyjv** [comment]
@jorisre there's no solution that I'm aware of besides checking if the error object is an array and handling it accordingly.

**Comment by bluebill1049** [comment]
closing it as design limitation.
