### ISSUE TITLE
Could validation with resolvers be broken?

### ISSUE THREAD

**Issue by alveshelio** [react-hook-form/resolvers#395]
**Describe the bug**
When using `react-hook-form` with `resolvers`,  `formState.errors` has objects but message is undefined.

**To Reproduce**
1. Go to ['...'](https://codesandbox.io/s/optimistic-sun-iqsg7g?file=/pages/index.tsx:0-2409)
2. enter an email in email
3. blur email field
4. The input gets a red border showing that the 

**Codesandbox link (Required)**
Here's the code sandbox: https://codesandbox.io/s/optimistic-sun-iqsg7g?file=/pages/index.tsx:0-2409

**Expected behavior**
The email input should not be on error since the test passes.

What's even weirder is that the issue only happens with the first input to be validated. If you start typing in password first, then it will be the password input that will be on error.

If you fill the first input, then you fill the next input and you click on the first input (the one who is on error) and blur the input again, then the error disappears.

When console.log(errors), I get this
```ts
{
  email: {
    message: undefined
    type: ""
    ref: <input type="text" name="email" class="form-control is-invalid" data-dashlane-rid="6556c0472a8723f3" data- 
     kwimpalastatus="alive" data-kwimpalaid="1650944299662-0" data-form-type="email"></input>
  }
}
```

**Comment by bluebill1049** [comment]
We are currently supporting vest v3, this could be related to v4 major update? @ealush any insight for the upgrade to v4?

**Comment by ealush** [comment]
@alveshelio thanks for reporting that, @bluebill1049 thank you for tagging me.

Yes, this seems to be a like a discrepancy in how v3 used to report back errors and how v4 does it. I released a patch that should maintain the compatibility with v3. The fix is in the specific method HookForm uses to query the errors (`result.getErrors()` - with no field parameter). Here is the entirety of the change: https://github.com/ealush/vest/commit/5acd20ca3af6e08a2a3f6ef3bec881aaf4350c83#diff-a3d8e00b38b30ad7858ec6b9b2fffce1f2d4e5a08e83eb25743c905dc2a06fa7R35-R38

@alveshelio, please upgrade to `vest@4.3.4` and report back if that fixes it for you. From my initial check against your sandbox it seems like it works correctly.

Apart from that I think we can consider some resolver adjustments to use the new v4 apis. @bluebill1049, what is your strategy for a major dependency upgrade? I refrained from making a PR updating vest to v4 here so it doesn't break for those who use v3.

**Comment by bluebill1049** [comment]
Thanks very much for the comment and replay @ealush 🙏 

> Apart from that I think we can consider some resolver adjustments to use the new v4 apis. @bluebill1049, what is your strategy for a major dependency upgrade? I refrained from making a PR updating vest to v4 here so it doesn't break for those who use v3.

That's awesome! ❤️ I think makes sense for the resolver to bump a major version as well if there is any breaking change for current vest v3 users, if not then we can stay with a minor version upgrade.

**Comment by alveshelio** [comment]
I can confirm that this has been resolved. Thank you both for the quick replay and fix. You guys rock :)
