### ISSUE TITLE
Add ajv-formats to the ajv resolver

### ISSUE THREAD

**Issue by jorgebarredo** [react-hook-form/resolvers#432]
**Is your feature request related to a problem? Please describe.**
A lot of people, including myself, use [ajv-formats](https://ajv.js.org/packages/ajv-formats.html) as an extension for ajv.

[ajv-formats](https://github.com/ajv-validator/ajv-formats) makes it easy and secure to validate *emails*, *urls*, *uuids*, and many others string formats. 

At the moment the ajv resolver does not include it, which means JSON Schemas properties with `format` do not compile and are 
 not validated.

I would like to highlight that [ajv-formats](https://github.com/ajv-validator/ajv-formats) is an official package under the ajv validator.

**Describe the solution you'd like**
Include ajv-formats as part of the ajv resolver.

**Describe alternatives you've considered**
Creating another ajv resolver with ajv-formats. I don't think this is the best idea, as adding ajv-formats by default does not cause any damage. The only thing it does is enhancing the grammar to support formats. Giving the the grammar is currently not "pure", because it already includes ajv-errors, I don't think this is a big issue.
Alternative implemented here: https://github.com/react-hook-form/resolvers/pull/434

**Additional context**
Change already implemented here in this PR: https://github.com/react-hook-form/resolvers/pull/431

**Comment by bluebill1049** [comment]
Going back to my original comment, please build a custom resolver for your use case. I don't think we prefer this external package to be a dep for everyone's use case with AJV.

**Comment by jorgebarredo** [comment]
Created PR with a custom ajv-formats resolver: https://github.com/react-hook-form/resolvers/pull/434

**Comment by bluebill1049** [comment]
sorry, I have confused you, I meant to use in your app level, not within this lib. thanks for the PR and sorry about the confusion.

**Comment by bluebill1049** [comment]
Sounds good to me, thanks for the willing to contribute and PRs 🙏

**Comment by vanhumbeecka** [comment]
This would be a great addition to this ajvResolver. I would argue that people use ajv and jsonschema _precisly_ because of very specific validation rule needs. Hence adding format-validation would make perfect sense. 
I do understand the trade-off being made here in favor of the more generic approach though...

**Comment by init-database** [comment]
these guys clearly don't like Ajv, they put it as the most bottom and the last one in the example section. you already include ajv-errors, why not for the ajv-formats? Yup has its validation for email, url, how do I validate those with ajv then? I already write ajv schema for my backend and I want to implement it in the frontend as well, I dont want to wasting my time write another validation rule in different ways

**Comment by iway1** [comment]
It's completely unnecessary to create a custom resolver, as `ajvResolver` accepts and `Ajv.Options` object as the second parameter which allows setting the formats on the AJV instance. You can import the formats from the ajv-formats library and pass them in. This works:

```jsx
import { ajvResolver } from "@hookform/resolvers/ajv";
import { fullFormats } from "ajv-formats/dist/formats";

function Form() {
  const { control: c, handleSubmit } = useForm({
    resolver: ajvResolver(myJsonSchema, {
      formats: fullFormats,
    }),
  });
  //...
}
```

That being said, I think this should be the default behavior of this resolver. Even just copy / pasting the formats from `ajv-resolver` into this library and passing them into the Ajv constructor would be super awesome. This is probably going to be a headache for a lot of people in the future because they will likely expect things like `format: email` to work out of the box, if I had to guess. IMO make it the default b/c it will ultimately save many people time =D

**Comment by GideonMax** [comment]
I feel like there should be an easier way to add plugins, something like:

```typescript
ajvResolver(myJsonSchema, {
      plugins: [require("ajv-formats"), require("ajv-keywords")]
    })
```
I don't see a reason to limit users from adding plugins.

**Comment by shane-js** [comment]
While this is closed I wanted to just add some context around @bluebill1049 comment which said:
>Going back to my original comment, please build a custom resolver for your use case. I don't think we prefer this external package to be a dep for everyone's use case with AJV.

Yes it is another package but I do think it is worthy to call out ajv-formats isn't some obscure random 3rd party - it is from the ajv-validator org itself: https://github.com/ajv-validator/ajv-formats & https://ajv.js.org/packages/ajv-formats.html. 

To paint a picture of overlap at time of writing this ajv-formats has ~20 million/week downloads on NPM and ajv itself ~100 million/week. So that's a fifth and how many things downstream from ajv have it as a dependency that inflate that number more than ajv-formats which would be closer to pure end user numbers such as those who would use something like react-hook-form (web app vs potentially inside libraries built on top of it/utilizing it). 

My admittedly meaningless vote if one were held was that it should be included or maybe some way to configure one time globally if it is possible (I am no too familiar with this project under the hood)

**Comment by lmossman** [comment]
I agree with the comment above — `ajv-formats` is a from the ajv-validator org, so it is a first-party package that makes sense to be included as the default behavior.

@bluebill1049 could you reconsider adding this to the ajvResolver?
