### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by stephenomas** [react-hook-form/resolvers#641]
i keep getting this error any time i try to build my nextjs app

Failed to compile.

./node_modules/@hookform/resolvers/yup/dist/yup.d.ts:3:138
Type error: '>' expected.

  1 | import * as Yup from 'yup';
  2 | import { FieldValues, Resolver } from 'react-hook-form';
> 3 | export declare function yupResolver<TFieldValues extends FieldValues>(schema: Yup.ObjectSchema<TFieldValues> | ReturnType<typeof Yup.lazy<Yup.ObjectSchema<TFieldValues>>>, schemaOptions?: Parameters<(typeof schema)['validate']>[1], resolverOptions?: {
    |                                                                                                                                          ^
  4 |     /**
  5 |      * @default async
  6 |      */

**Comment by EvanAgee** [comment]
Same here.

**Comment by jorisre** [comment]
Can you provide a Codesandbox with the issue? thank you

**Comment by antonsolversio** [comment]
Any updates or solutions? I have same issue

**Comment by keithrz** [comment]
I was seeing this error in my project, and it was because I had an older version of TypeScript.  I was on TS 4.2.x

It looks like the "bad" TypeScript mentioned in this issue relies on a feature added in TypeScript 4.7: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#instantiation-expressions

After upgrading to TypeScript 4.7.4, the issue went away.

**Comment by stefdomandtom** [comment]
@keithrz thank you so much

**Comment by jorisre** [comment]
It appears @keithrz's [solution](https://github.com/react-hook-form/resolvers/issues/641#issuecomment-1892686793) has resolved the issue. Closing this now.
